// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: continente.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetingServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre     string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Apellido   string `protobuf:"bytes,2,opt,name=apellido,proto3" json:"apellido,omitempty"`
	EstaMuerto bool   `protobuf:"varint,3,opt,name=EstaMuerto,proto3" json:"EstaMuerto,omitempty"`
}

func (x *GreetingServiceRequest) Reset() {
	*x = GreetingServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_continente_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetingServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingServiceRequest) ProtoMessage() {}

func (x *GreetingServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_continente_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingServiceRequest.ProtoReflect.Descriptor instead.
func (*GreetingServiceRequest) Descriptor() ([]byte, []int) {
	return file_continente_proto_rawDescGZIP(), []int{0}
}

func (x *GreetingServiceRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *GreetingServiceRequest) GetApellido() string {
	if x != nil {
		return x.Apellido
	}
	return ""
}

func (x *GreetingServiceRequest) GetEstaMuerto() bool {
	if x != nil {
		return x.EstaMuerto
	}
	return false
}

type GreetingServiceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GreetingServiceReply) Reset() {
	*x = GreetingServiceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_continente_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetingServiceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingServiceReply) ProtoMessage() {}

func (x *GreetingServiceReply) ProtoReflect() protoreflect.Message {
	mi := &file_continente_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingServiceReply.ProtoReflect.Descriptor instead.
func (*GreetingServiceReply) Descriptor() ([]byte, []int) {
	return file_continente_proto_rawDescGZIP(), []int{1}
}

func (x *GreetingServiceReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DataNodeServiceStorage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	EstaMuerto bool   `protobuf:"varint,6,opt,name=EstaMuerto,proto3" json:"EstaMuerto,omitempty"`
}

func (x *DataNodeServiceStorage) Reset() {
	*x = DataNodeServiceStorage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_continente_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataNodeServiceStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNodeServiceStorage) ProtoMessage() {}

func (x *DataNodeServiceStorage) ProtoReflect() protoreflect.Message {
	mi := &file_continente_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNodeServiceStorage.ProtoReflect.Descriptor instead.
func (*DataNodeServiceStorage) Descriptor() ([]byte, []int) {
	return file_continente_proto_rawDescGZIP(), []int{2}
}

func (x *DataNodeServiceStorage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataNodeServiceStorage) GetEstaMuerto() bool {
	if x != nil {
		return x.EstaMuerto
	}
	return false
}

var File_continente_proto protoreflect.FileDescriptor

var file_continente_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x65, 0x6e, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x16, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f,
	0x6d, 0x62, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x70, 0x65, 0x6c, 0x6c, 0x69, 0x64, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x70, 0x65, 0x6c, 0x6c, 0x69, 0x64, 0x6f,
	0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x73, 0x74, 0x61, 0x4d, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x45, 0x73, 0x74, 0x61, 0x4d, 0x75, 0x65, 0x72, 0x74, 0x6f,
	0x22, 0x30, 0x0a, 0x14, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x48, 0x0a, 0x16, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x45, 0x73, 0x74, 0x61, 0x4d, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x45, 0x73, 0x74, 0x61, 0x4d, 0x75, 0x65, 0x72, 0x74, 0x6f, 0x32, 0x4f, 0x0a, 0x0f,
	0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3c, 0x0a, 0x08, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x17, 0x2e, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x32, 0x4e, 0x0a,
	0x0f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x1a, 0x15, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x05, 0x5a,
	0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_continente_proto_rawDescOnce sync.Once
	file_continente_proto_rawDescData = file_continente_proto_rawDesc
)

func file_continente_proto_rawDescGZIP() []byte {
	file_continente_proto_rawDescOnce.Do(func() {
		file_continente_proto_rawDescData = protoimpl.X.CompressGZIP(file_continente_proto_rawDescData)
	})
	return file_continente_proto_rawDescData
}

var file_continente_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_continente_proto_goTypes = []interface{}{
	(*GreetingServiceRequest)(nil), // 0: GreetingServiceRequest
	(*GreetingServiceReply)(nil),   // 1: GreetingServiceReply
	(*DataNodeServiceStorage)(nil), // 2: DataNodeServiceStorage
}
var file_continente_proto_depIdxs = []int32{
	0, // 0: GreetingService.Greeting:input_type -> GreetingServiceRequest
	2, // 1: DataNodeService.Storage:input_type -> DataNodeServiceStorage
	1, // 2: GreetingService.Greeting:output_type -> GreetingServiceReply
	1, // 3: DataNodeService.Storage:output_type -> GreetingServiceReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_continente_proto_init() }
func file_continente_proto_init() {
	if File_continente_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_continente_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetingServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_continente_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetingServiceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_continente_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataNodeServiceStorage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_continente_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_continente_proto_goTypes,
		DependencyIndexes: file_continente_proto_depIdxs,
		MessageInfos:      file_continente_proto_msgTypes,
	}.Build()
	File_continente_proto = out.File
	file_continente_proto_rawDesc = nil
	file_continente_proto_goTypes = nil
	file_continente_proto_depIdxs = nil
}
